---
title: Reproducible research with R, Quarto, renv and GitHub
subtitle: TODO
categories: [R, quarto, reproducibility]
date: "2024-04-14"
draft: true
---

In this post I teach myself how to create a new reproducible project.

## Quarto website project with Rstudio

-   select renv and version control
-   I already have my github credentials set, but can link to a resource

## yaml settings

some of these are not on by default, explain them

-   output-dir

-   execute-dir

-   freeze: auto

-   code-link: true

``` yaml
project:
  type: website
  output-dir: docs
  execute-dir: project
  
execute:
  freeze: auto

website:
  title: "Parameter recovery"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-link: true

editor: visual
```

## renv

Why? Ensures package versions will make code run. Local links in folder

for new projects

-   renv::init()

-   renv::install()

-   renv::snapshot()

-   commit renv.lock

For collaborators or new machines:

-   Restore the project environment with `renv::restore()`

-   Run `renv::install()` to install the new package

-   Update the Lockfile with `renv::snapshot()`

-   Commit `renv.lock` with your changes

seems that Rstudio selecting renv and git does not apply renv ignore to the base file?

on website it says: "After installing the package and checking that your code works, you should call [`renv::snapshot()`](https://rstudio.github.io/renv/reference/snapshot.html) to record the latest package versions in your lockfile. If you’re collaborating with others, you’ll need to commit those changes to git, and let them know that you’ve updated the lockfile and they should call [`renv::restore()`](https://rstudio.github.io/renv/reference/restore.html) when they’re next working on a project"

is this really necessary? Shouldn't renv recognize that new dependencies are listed and prompt this?

## Folder setup

-   data

-   output

-   notebooks

## Large file storage
